# Site settings
title:  Mundim da Educação
email: leandroresendemundim@gmail.com
description: Plataforma de cursos
baseurl: "" 
url: "https://leandromundim.github.io" 
twitter_username: drmundim
github_username:  drmundim

# User settings
username: Leandro Mundim
user_description: Pesquisador e estudante
email: leandroresendemundim@gmail.com
twitter_username: drmundim
github_username:  drmundim

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Cursos
    url: /cursos
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /about

collections:
  - cursos

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby']
