# Site settings
title: Leandro R. Mundim
description: Plataforma de cursos
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leandromundim.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Leandro R. Mundim
user_description: Pesquisador e professor
email: leandroresendemundim@gmail.com
twitter_username: drmundim
github_username:  drmundim

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Inicial
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /about/

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
